# -*- coding: utf-8 -*-
"""Part-3-Regional-Performance-Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FoD_M_f72cTQEX3SITr6mfAMUdkWXDf_

# PART 3: REGIONAL PERFORMANCE INSIGHTS
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Merged_orders.csv")
df.head()

top_states = df['State'].value_counts().head(5).index
top_states

top_states_fil = df[df['State'].isin(top_states)]
state_result = top_states_fil.groupby('State').agg(
    Totalorder = ('Order ID','count'),
    Totalsales = ('Amount','sum'),
    Avgprofit = ('Profit','mean'),
).reset_index().sort_values(by='Totalorder',ascending=False)
state_result

"""# Top 5 States with higher Order
1. Madhya Pradesh
2. Maharastra
3. Gujarat
4. Delhi
5. Rajasthan
"""

region_result = df.groupby(['State','City']).agg(
    Totalsales = ('Amount','sum'),
    Totalprofit = ('Profit','sum'),
    Avgprofit = ('Profit','mean'),
    Totalorder = ('Order ID','count'),
).reset_index()

low_perform = region_result[(region_result['Totalsales']<region_result['Totalsales'].median()) | (region_result['Totalprofit']< region_result['Totalprofit'].median())]
low_perform = low_perform.sort_values(by='Totalprofit')
low_perform

"""# Regional Disparities in Sales and Profitability
1. Chennai from Tamil Nadu
2. Chandigarh from Punjab
3. Ahmedabad from Gujarat
4. Jaipur from Rajasthan
5. Hyderabad from Andhra Pradesh
6. Patna from Bihar

These city's sales face a lot of loss in the total sales order and profit where in chennai there only 25 orders where placed and it's total profit is negative(-2216) which means there is no profit margin in that region so we have to cross-check operational costs, heavy discounting, or low pricing strategies responsible for the losses. Focus on product pricing and higher-margin product lines.
"""

high_perform = low_perform.sort_values(by='Avgprofit',ascending= False)
high_perform

"""# Regions Positive in Profitability
1. Delhi from Madhya Pradesh
2. Udaipur from Rajasthan
3. Surat from Gujarat
4. Chandigarh from Haryana

These cities have good profitability but have less than 30 orders whereas Delhi has an average profit of '74.42' but only has 7 orders so focus on promoting products in these areas to gain more profits and plan strategies to attract more customers to change underperforming areas into a leading sales figures.

Cities like Udaipur and Jaipur from Rajasthan and Surat and Ahmedabad from Gujarat have different profit stats but in the same state. We also analyzed and find what was the reason for that difference and tried to apply some strategies to improve sales in low-performing regions.
"""

